name: coding standards

on:
    push:
        branches: [main, master, '2.x']
    pull_request:
        branches: [main, master, '2.x']

permissions:
    contents: read

jobs:
    pint:
        runs-on: ubuntu-latest
        name: Pint

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction --no-progress

            - name: Check code style
              run: vendor/bin/pint --test
